cortex:
  url: ""
  username: ""
  password: ""

github:
  key: ""

incidentio:
  key: ""

resources:
  main:
    requests:
      cpu: 2m
      memory: 20Mi
    limits:
      cpu: 50m
      memory: 200Mi
  grafanaAgent:
    requests:
      cpu: 8m
      memory: 50Mi
    limits:
      cpu: 50m
      memory: 200Mi
